/**
 * GENERATED FILE — do not hand-edit.
 *
 * Generated by web/scripts/sync-version.mjs from src/langarian/version.py.
 * The Python kernel version manifest is the single source of truth;
 * conformance tests fail on any divergence.
 */

export const VERSION_MANIFEST = {
  product_version: "0.3.0-rc.1",
  kernel_version: "langarian-python-ref-v0.3.0",
  model_version: "langarian-finite-complex-model-v0.2.1",
  metric_version: "metric:v0.3.scale_safe_normalized_complex_similarity",
  receipt_schema_version: "receipt:v0.3",
  dsl_version: "langarian-dsl:v0.3",
  fixture_version: "fixtures:v0.3",
  ts_port_version: "langarian-ts-port-v0.3.0",
  visualization_version: "viz:v0.3",
} as const

export const PRODUCT_VERSION = VERSION_MANIFEST.product_version
export const KERNEL_VERSION = VERSION_MANIFEST.kernel_version
export const MODEL_VERSION = VERSION_MANIFEST.model_version
export const METRIC_VERSION = VERSION_MANIFEST.metric_version
export const RECEIPT_SCHEMA_VERSION = VERSION_MANIFEST.receipt_schema_version
export const DSL_VERSION = VERSION_MANIFEST.dsl_version
export const FIXTURE_VERSION = VERSION_MANIFEST.fixture_version
export const TS_PORT_VERSION = VERSION_MANIFEST.ts_port_version
export const VISUALIZATION_VERSION = VERSION_MANIFEST.visualization_version

/** Python kernel version mirrored by this TypeScript port. */
export const PYTHON_KERNEL_VERSION_MIRRORED = VERSION_MANIFEST.kernel_version

/** Versions accepted on receipt import/validation (no silent downgrade). */
export const ALLOWED_KERNEL_VERSIONS: ReadonlySet<string> = new Set([KERNEL_VERSION])
export const ALLOWED_METRIC_VERSIONS: ReadonlySet<string> = new Set([METRIC_VERSION])
export const ALLOWED_RECEIPT_SCHEMA_VERSIONS: ReadonlySet<string> = new Set([RECEIPT_SCHEMA_VERSION])
