#!/usr/bin/env node
/**
 * Generate web/src/kernel/version.ts from the single-source Python manifest
 * (src/langarian/version.py) and cross-check the conformance fixture manifest
 * (fixtures/conformance/manifest.json). Divergence is a hard failure.
 *
 * Never hand-edit the generated file.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const webDir = dirname(dirname(fileURLToPath(import.meta.url)))
const repoRoot = dirname(webDir)
const versionPyPath = join(repoRoot, 'src', 'langarian', 'version.py')
const fixtureManifestPath = join(repoRoot, 'fixtures', 'conformance', 'manifest.json')
const outPath = join(webDir, 'src', 'kernel', 'version.ts')

const source = readFileSync(versionPyPath, 'utf8')

// Parse entries of the form: "key": "value", inside the VERSION_MANIFEST dict.
const manifestMatch = source.match(/VERSION_MANIFEST:\s*dict\[str,\s*str\]\s*=\s*\{([\s\S]*?)\}/)
if (!manifestMatch) {
  console.error(`sync-version: could not locate VERSION_MANIFEST dict in ${versionPyPath}`)
  process.exit(1)
}
const entryRe = /"([a-z_]+)":\s*"([^"]+)"/g
const manifest = {}
for (const match of manifestMatch[1].matchAll(entryRe)) {
  manifest[match[1]] = match[2]
}

const REQUIRED_KEYS = [
  'product_version',
  'kernel_version',
  'model_version',
  'metric_version',
  'receipt_schema_version',
  'dsl_version',
  'fixture_version',
  'ts_port_version',
  'visualization_version',
]
for (const key of REQUIRED_KEYS) {
  if (!(key in manifest)) {
    console.error(`sync-version: missing key "${key}" in VERSION_MANIFEST`)
    process.exit(1)
  }
}

// Cross-check the conformance fixture manifest against the Python manifest.
const fixtureManifest = JSON.parse(readFileSync(fixtureManifestPath, 'utf8'))
const crossChecks = ['fixture_version', 'kernel_version', 'metric_version', 'receipt_schema_version']
const mismatches = crossChecks.filter((key) => fixtureManifest[key] !== manifest[key])
if (mismatches.length > 0) {
  for (const key of mismatches) {
    console.error(
      `sync-version: fixture manifest ${key}=${JSON.stringify(fixtureManifest[key])} ` +
        `does not match version.py ${key}=${JSON.stringify(manifest[key])}`,
    )
  }
  process.exit(1)
}

const lines = []
lines.push('/**')
lines.push(' * GENERATED FILE — do not hand-edit.')
lines.push(' *')
lines.push(' * Generated by web/scripts/sync-version.mjs from src/langarian/version.py.')
lines.push(' * The Python kernel version manifest is the single source of truth;')
lines.push(' * conformance tests fail on any divergence.')
lines.push(' */')
lines.push('')
lines.push('export const VERSION_MANIFEST = {')
for (const key of REQUIRED_KEYS) {
  lines.push(`  ${key}: ${JSON.stringify(manifest[key])},`)
}
lines.push('} as const')
lines.push('')
for (const key of REQUIRED_KEYS) {
  const constName = key.toUpperCase()
  lines.push(`export const ${constName} = VERSION_MANIFEST.${key}`)
}
lines.push('')
lines.push('/** Python kernel version mirrored by this TypeScript port. */')
lines.push('export const PYTHON_KERNEL_VERSION_MIRRORED = VERSION_MANIFEST.kernel_version')
lines.push('')
lines.push('/** Versions accepted on receipt import/validation (no silent downgrade). */')
lines.push('export const ALLOWED_KERNEL_VERSIONS: ReadonlySet<string> = new Set([KERNEL_VERSION])')
lines.push('export const ALLOWED_METRIC_VERSIONS: ReadonlySet<string> = new Set([METRIC_VERSION])')
lines.push('export const ALLOWED_RECEIPT_SCHEMA_VERSIONS: ReadonlySet<string> = new Set([RECEIPT_SCHEMA_VERSION])')
lines.push('')

writeFileSync(outPath, lines.join('\n'), 'utf8')
console.log(`sync-version: wrote ${outPath}`)
console.log(
  `sync-version: python_kernel_version_mirrored=${manifest.kernel_version} ts_port_version=${manifest.ts_port_version}`,
)
